set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER x86_64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER x86_64-linux-gnu-g++)
set(CMAKE_SYSTEM_PROCESSOR amd64)

set(ENV{OPENSSL_ROOT_DIR} "/usr/x86_64-linux-gnu;/usr/lib/x86_64-linux-gnu")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
