SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_C_COMPILER powerpc64le-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER powerpc64le-linux-gnu-g++)
SET(CMAKE_SYSTEM_PROCESSOR ppc64el)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
