SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_C_COMPILER s390x-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER s390x-linux-gnu-g++)
SET(CMAKE_SYSTEM_PROCESSOR s390x)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
