name: blufi
title: Blufi
base: core22
# compression
version: git
contact: zxf1023818103@gmail.com
# donation
issues: https://github.com/zxf1023818103/blufi/issues
source-code: https://github.com/zxf1023818103/blufi.git
website: https://github.com/zxf1023818103/blufi
summary: Blufi Client and Server Applications
description: Configure Wi-Fi network for IoT device via Bluetooth channel through Blufi protocol.
type: app
confinement: devmode # use 'strict' once you have the right plugs and slots
# icon:
# layout:
license: GPL-3.0
grade: devel # must be 'stable' to release into candidate/stable channels
# adopt-info
architectures:
  - build-on: [amd64, i386, arm64, armhf]
    build-for: amd64
  - build-on: [amd64, i386, arm64, armhf]
    build-for: i386
  - build-on: [amd64, i386, arm64, armhf]
    build-for: arm64
  - build-on: [amd64, i386, arm64, armhf]
    build-for: armhf
# assumes:
# hooks:
apps:
  bluficlient:
    command: usr/local/bin/bluficlient
    plugs:
      - bluez
      #- network-bind
      - network-control
      #- network-observe
  
  blufiserver:
    command: usr/local/bin/blufiserver
    plugs:
      - bluez
      - network-manager

parts:
  blufi:
    plugin: cmake
    source: .
    build-packages:
      - build-essential
      - cmake
      - qt6-base-dev
      - qt6-connectivity-dev
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - qt6-l10n-tools
      - libssl-dev
    stage-packages:
      - libqt6core6
      - libqt6bluetooth6
      - libssl3